#buildspec.yaml used by AWS CodeBuild
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16.15.1

    commands:
        # install npm
        - npm install

  build:
    commands:
        # run "build" script in package.json
        - npm run build
